name: Build Packages

on:
  push:
    paths-ignore:
      - '.github/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build ./GroupDocs.Viewer.Cli.sln

      - name: Run tests
        run: dotnet test ./GroupDocs.Viewer.Cli.sln --no-build
