name: Publish Prod
on:
 workflow_dispatch:  

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build -c Release src/GroupDocs.Viewer.Cli/GroupDocs.Viewer.Cli.csproj

      - name: Pack
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/GroupDocs.Viewer.Cli/GroupDocs.Viewer.Cli.csproj -o .

      - name: Publish
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN} --skip-duplicate 
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY_PROD }}
